.text:00401000 ;
.text:00401000 ; +-------------------------------------------------------------------------+
.text:00401000 ; |   This file has been	generated by The Interactive Disassembler (IDA)	   |
.text:00401000 ; |	     Copyright (c) 2015	Hex-Rays, <support@hex-rays.com>	   |
.text:00401000 ; |			License	info: 48-B611-7234-BB			   |
.text:00401000 ; |	       Doskey Lee, Kingsoft Internet Security Software		   |
.text:00401000 ; +-------------------------------------------------------------------------+
.text:00401000 ;
.text:00401000 ; Input MD5   : E23C79510CD95A6FCC796FB59D689EA8
.text:00401000 ; Input CRC32 : 448D6FB8
.text:00401000
.text:00401000 ; File Name   : C:\Users\John\Desktop\test\Win32Project1.exe
.text:00401000 ; Format	     : Portable	executable for 80386 (PE)
.text:00401000 ; Imagebase   : 400000
.text:00401000 ; Section 1. (virtual address 00001000)
.text:00401000 ; Virtual size		       : 00000844 (   2116.)
.text:00401000 ; Section size in file	       : 00000A00 (   2560.)
.text:00401000 ; Offset	to raw data for	section: 00000400
.text:00401000 ; Flags 60000020: Text Executable Readable
.text:00401000 ; Alignment     : default
.text:00401000 ; PDB File Name : C:\Users\John\Desktop\Win32Project1\Release\Win32Project1.pdb
.text:00401000 ; OS type	 :  MS Windows
.text:00401000 ; Application type:  Executable 32bit
.text:00401000
.text:00401000		       include uni.inc ; see unicode subdir of ida for info on unicode
.text:00401000
.text:00401000		       .686p
.text:00401000		       .mmx
.text:00401000		       .model flat
.text:00401000
.text:00401000 ; ===========================================================================
.text:00401000
.text:00401000 ; Segment type: Pure code
.text:00401000 ; Segment permissions: Read/Execute
.text:00401000 _text	       segment para public 'CODE' use32
.text:00401000		       assume cs:_text
.text:00401000		       ;org 401000h
.text:00401000		       assume es:nothing, ss:nothing, ds:_data,	fs:nothing, gs:nothing
.text:00401000
.text:00401000 ; =============== S U B R O U T I N E =======================================
.text:00401000
.text:00401000
.text:00401000 ; int __cdecl main(int argc, const char **argv, const char **envp)
.text:00401000 _main	       proc near	       ; CODE XREF: __tmainCRTStartup+F8p
.text:00401000
.text:00401000 argc	       = dword ptr  8
.text:00401000 argv	       = dword ptr  0Ch
.text:00401000
.text:00401000		       push    offset Format   ; "Hello	World!\n"
.text:00401005		       call    ds:__imp__wprintf
.text:0040100B		       add     esp, 4
.text:0040100E		       xor     eax, eax
.text:00401010		       retn
.text:00401010 _main	       endp
.text:00401010
.text:00401011 ; [0000000F BYTES: COLLAPSED FUNCTION __security_check_cookie(x)]
.text:00401020 ; [000000B9 BYTES: COLLAPSED FUNCTION pre_c_init]
.text:004010D9 ; [0000004B BYTES: COLLAPSED FUNCTION pre_cpp_init]
.text:00401124 ; [00000165 BYTES: COLLAPSED FUNCTION __tmainCRTStartup]
.text:00401289 ; [0000000A BYTES: COLLAPSED FUNCTION _wmainCRTStartup]
.text:00401293 ; [0000003D BYTES: COLLAPSED FUNCTION ___raise_securityfailure]
.text:004012D0 ; [000000FB BYTES: COLLAPSED FUNCTION ___report_gsfailure]
.text:004013CB ; [00000040 BYTES: COLLAPSED FUNCTION __CxxUnhandledExceptionFilter(_EXCEPTION_POINTERS *)]
.text:0040140B $LN8	       db 0CCh
.text:0040140C ; [0000000E BYTES: COLLAPSED FUNCTION ___CxxSetUnhandledExceptionFilter]
.text:0040141A ; [00000006 BYTES: COLLAPSED FUNCTION __XcptFilter]
.text:00401420 ; [00000006 BYTES: COLLAPSED FUNCTION __amsg_exit]
.text:00401426		       align 10h
.text:00401430
.text:00401430 ; =============== S U B R O U T I N E =======================================
.text:00401430
.text:00401430 ; Attributes: bp-based frame
.text:00401430
.text:00401430 ; _IMAGE_SECTION_HEADER *__cdecl	_FindPESection(char *pImageBase, unsigned int rva)
.text:00401430 __FindPESection proc near	       ; CODE XREF: __IsNonwritableInCurrentImage+59p
.text:00401430
.text:00401430 pImageBase      = dword ptr  8
.text:00401430 rva	       = dword ptr  0Ch
.text:00401430
.text:00401430		       push    ebp
.text:00401431		       mov     ebp, esp
.text:00401433		       mov     eax, [ebp+pImageBase]
.text:00401436		       xor     edx, edx
.text:00401438		       push    ebx
.text:00401439		       push    esi
.text:0040143A		       push    edi
.text:0040143B		       mov     ecx, [eax+3Ch]
.text:0040143E		       add     ecx, eax
.text:00401440		       movzx   eax, word ptr [ecx+14h]
.text:00401444		       movzx   ebx, word ptr [ecx+6]
.text:00401448		       add     eax, 18h
.text:0040144B		       add     eax, ecx
.text:0040144D		       test    ebx, ebx
.text:0040144F		       jz      short loc_40146C
.text:00401451		       mov     edi, [ebp+rva]
.text:00401454
.text:00401454 loc_401454:			       ; CODE XREF: __FindPESection+3Aj
.text:00401454		       mov     esi, [eax+0Ch]
.text:00401457		       cmp     edi, esi
.text:00401459		       jb      short loc_401464
.text:0040145B		       mov     ecx, [eax+8]
.text:0040145E		       add     ecx, esi
.text:00401460		       cmp     edi, ecx
.text:00401462		       jb      short loc_40146E
.text:00401464
.text:00401464 loc_401464:			       ; CODE XREF: __FindPESection+29j
.text:00401464		       inc     edx
.text:00401465		       add     eax, 28h
.text:00401468		       cmp     edx, ebx
.text:0040146A		       jb      short loc_401454
.text:0040146C
.text:0040146C loc_40146C:			       ; CODE XREF: __FindPESection+1Fj
.text:0040146C		       xor     eax, eax
.text:0040146E
.text:0040146E loc_40146E:			       ; CODE XREF: __FindPESection+32j
.text:0040146E		       pop     edi
.text:0040146F		       pop     esi
.text:00401470		       pop     ebx
.text:00401471		       pop     ebp
.text:00401472		       retn
.text:00401472 __FindPESection endp
.text:00401472
.text:00401472 ; ---------------------------------------------------------------------------
.text:00401473		       align 10h
.text:00401480 ; [000000BA BYTES: COLLAPSED FUNCTION __IsNonwritableInCurrentImage]
.text:0040153A		       align 10h
.text:00401540 ; [00000031 BYTES: COLLAPSED FUNCTION __ValidateImageBase]
.text:00401571
.text:00401571 ; =============== S U B R O U T I N E =======================================
.text:00401571
.text:00401571 ; Attributes: bp-based frame
.text:00401571
.text:00401571 ___security_init_cookie proc near       ; CODE XREF: _wmainCRTStartupp
.text:00401571
.text:00401571 perfctr	       = _LARGE_INTEGER	ptr -14h
.text:00401571 systime	       = FT ptr	-0Ch
.text:00401571 cookie	       = dword ptr -4
.text:00401571
.text:00401571		       push    ebp
.text:00401572		       mov     ebp, esp
.text:00401574		       sub     esp, 14h
.text:00401577		       and     dword ptr [ebp+systime],	0
.text:0040157B		       and     dword ptr [ebp+systime+4], 0
.text:0040157F		       mov     eax, ___security_cookie
.text:00401584		       push    esi
.text:00401585		       push    edi
.text:00401586		       mov     edi, 0BB40E64Eh
.text:0040158B		       mov     esi, 0FFFF0000h
.text:00401590		       cmp     eax, edi
.text:00401592		       jz      short loc_4015A1
.text:00401594		       test    esi, eax
.text:00401596		       jz      short loc_4015A1
.text:00401598		       not     eax
.text:0040159A		       mov     ___security_cookie_complement, eax
.text:0040159F		       jmp     short loc_401607
.text:004015A1 ; ---------------------------------------------------------------------------
.text:004015A1
.text:004015A1 loc_4015A1:			       ; CODE XREF: ___security_init_cookie+21j
.text:004015A1					       ; ___security_init_cookie+25j
.text:004015A1		       lea     eax, [ebp+systime]
.text:004015A4		       push    eax	       ; lpSystemTimeAsFileTime
.text:004015A5		       call    ds:__imp__GetSystemTimeAsFileTime@4 ; GetSystemTimeAsFileTime(x)
.text:004015AB		       mov     eax, dword ptr [ebp+systime+4]
.text:004015AE		       xor     eax, dword ptr [ebp+systime]
.text:004015B1		       mov     [ebp+cookie], eax
.text:004015B4		       call    ds:__imp__GetCurrentThreadId@0 ;	GetCurrentThreadId()
.text:004015BA		       xor     [ebp+cookie], eax
.text:004015BD		       call    ds:__imp__GetCurrentProcessId@0 ; GetCurrentProcessId()
.text:004015C3		       xor     [ebp+cookie], eax
.text:004015C6		       lea     eax, [ebp+perfctr]
.text:004015C9		       push    eax	       ; lpPerformanceCount
.text:004015CA		       call    ds:__imp__QueryPerformanceCounter@4 ; QueryPerformanceCounter(x)
.text:004015D0		       mov     ecx, dword ptr [ebp+perfctr+4]
.text:004015D3		       lea     eax, [ebp+cookie]
.text:004015D6		       xor     ecx, dword ptr [ebp+perfctr]
.text:004015D9		       xor     ecx, [ebp+cookie]
.text:004015DC		       xor     ecx, eax
.text:004015DE		       cmp     ecx, edi
.text:004015E0		       jnz     short loc_4015E9
.text:004015E2		       mov     ecx, 0BB40E64Fh
.text:004015E7		       jmp     short loc_4015F9
.text:004015E9 ; ---------------------------------------------------------------------------
.text:004015E9
.text:004015E9 loc_4015E9:			       ; CODE XREF: ___security_init_cookie+6Fj
.text:004015E9		       test    esi, ecx
.text:004015EB		       jnz     short loc_4015F9
.text:004015ED		       mov     eax, ecx
.text:004015EF		       or      eax, 4711h
.text:004015F4		       shl     eax, 10h
.text:004015F7		       or      ecx, eax
.text:004015F9
.text:004015F9 loc_4015F9:			       ; CODE XREF: ___security_init_cookie+76j
.text:004015F9					       ; ___security_init_cookie+7Aj
.text:004015F9		       mov     ___security_cookie, ecx
.text:004015FF		       not     ecx
.text:00401601		       mov     ___security_cookie_complement, ecx
.text:00401607
.text:00401607 loc_401607:			       ; CODE XREF: ___security_init_cookie+2Ej
.text:00401607		       pop     edi
.text:00401608		       pop     esi
.text:00401609		       mov     esp, ebp
.text:0040160B		       pop     ebp
.text:0040160C		       retn
.text:0040160C ___security_init_cookie endp
.text:0040160C
.text:0040160D
.text:0040160D ; =============== S U B R O U T I N E =======================================
.text:0040160D
.text:0040160D
.text:0040160D ; int __cdecl _wsetargv()
.text:0040160D __wsetargv      proc near	       ; CODE XREF: pre_c_init+85p
.text:0040160D					       ; DATA XREF: pre_c_init+93o
.text:0040160D
.text:0040160D pexcept	       = dword ptr  8
.text:0040160D
.text:0040160D		       xor     eax, eax
.text:0040160F		       retn
.text:0040160F __wsetargv      endp
.text:0040160F
.text:00401610 ; [0000003C BYTES: COLLAPSED FUNCTION ___atonexitinit]
.text:0040164C
.text:0040164C ; =============== S U B R O U T I N E =======================================
.text:0040164C
.text:0040164C ; Attributes: bp-based frame
.text:0040164C
.text:0040164C ; int (__cdecl *__cdecl _onexit(int (__cdecl *func)()))()
.text:0040164C __onexit	       proc near	       ; CODE XREF: _atexit+6p
.text:0040164C
.text:0040164C retval	       = dword ptr -24h
.text:0040164C onexitend       = dword ptr -20h
.text:0040164C onexitbegin     = dword ptr -1Ch
.text:0040164C ms_exc	       = CPPEH_RECORD ptr -18h
.text:0040164C func	       = dword ptr  8
.text:0040164C
.text:0040164C		       push    14h
.text:0040164E		       push    offset stru_402238
.text:00401653		       call    __SEH_prolog4
.text:00401658		       and     [ebp+retval], 0
.text:0040165C		       push    ___onexitbegin  ; Ptr
.text:00401662		       mov     esi, ds:__imp__DecodePointer@4 ;	DecodePointer(x)
.text:00401668		       call    esi ; DecodePointer(x) ;	DecodePointer(x)
.text:0040166A		       mov     [ebp+onexitbegin], eax
.text:0040166D		       cmp     eax, 0FFFFFFFFh
.text:00401670		       jnz     short loc_40167E
.text:00401672		       push    [ebp+func]      ; Func
.text:00401675		       call    ds:__imp___onexit
.text:0040167B		       pop     ecx
.text:0040167C		       jmp     short loc_4016E3
.text:0040167E ; ---------------------------------------------------------------------------
.text:0040167E
.text:0040167E loc_40167E:			       ; CODE XREF: __onexit+24j
.text:0040167E		       push    8
.text:00401680		       call    __lock
.text:00401685		       pop     ecx
.text:00401686		       and     [ebp+ms_exc.registration.TryLevel], 0
.text:0040168A		       push    ___onexitbegin  ; Ptr
.text:00401690		       call    esi ; DecodePointer(x) ;	DecodePointer(x)
.text:00401692		       mov     [ebp+onexitbegin], eax
.text:00401695		       push    ___onexitend    ; Ptr
.text:0040169B		       call    esi ; DecodePointer(x) ;	DecodePointer(x)
.text:0040169D		       mov     [ebp+onexitend],	eax
.text:004016A0		       lea     eax, [ebp+onexitend]
.text:004016A3		       push    eax
.text:004016A4		       lea     eax, [ebp+onexitbegin]
.text:004016A7		       push    eax
.text:004016A8		       push    [ebp+func]      ; Ptr
.text:004016AB		       mov     esi, ds:__imp__EncodePointer@4 ;	EncodePointer(x)
.text:004016B1		       call    esi ; EncodePointer(x) ;	EncodePointer(x)
.text:004016B3		       push    eax
.text:004016B4		       call    ___dllonexit
.text:004016B9		       add     esp, 0Ch
.text:004016BC		       mov     edi, eax
.text:004016BE		       mov     [ebp+retval], edi
.text:004016C1		       push    [ebp+onexitbegin] ; Ptr
.text:004016C4		       call    esi ; EncodePointer(x) ;	EncodePointer(x)
.text:004016C6		       mov     ___onexitbegin, eax
.text:004016CB		       push    [ebp+onexitend] ; Ptr
.text:004016CE		       call    esi ; EncodePointer(x) ;	EncodePointer(x)
.text:004016D0		       mov     ___onexitend, eax
.text:004016D5		       mov     [ebp+ms_exc.registration.TryLevel], 0FFFFFFFEh
.text:004016DC		       call    $LN8_1
.text:004016E1 ; ---------------------------------------------------------------------------
.text:004016E1
.text:004016E1 $LN9:				       ; CODE XREF: __onexit:$LN7_0j
.text:004016E1		       mov     eax, edi
.text:004016E3
.text:004016E3 loc_4016E3:			       ; CODE XREF: __onexit+30j
.text:004016E3		       call    __SEH_epilog4
.text:004016E8		       retn
.text:004016E9 ; ---------------------------------------------------------------------------
.text:004016E9
.text:004016E9 $LN6:				       ; DATA XREF: .rdata:stru_402238o
.text:004016E9		       mov     edi, [ebp+retval] ; Finally handler 0 for function 40164C
.text:004016EC
.text:004016EC $LN8_1:				       ; CODE XREF: __onexit+90j
.text:004016EC		       push    8
.text:004016EE		       call    __unlock
.text:004016F3		       pop     ecx
.text:004016F4
.text:004016F4 $LN7_0:
.text:004016F4		       retn
.text:004016F4 __onexit	       endp
.text:004016F4
.text:004016F5
.text:004016F5 ; =============== S U B R O U T I N E =======================================
.text:004016F5
.text:004016F5 ; Attributes: bp-based frame
.text:004016F5
.text:004016F5 ; int __cdecl atexit(void (__cdecl *func)())
.text:004016F5 _atexit	       proc near	       ; CODE XREF: pre_cpp_init+5p
.text:004016F5
.text:004016F5 func	       = dword ptr  8
.text:004016F5
.text:004016F5		       push    ebp
.text:004016F6		       mov     ebp, esp
.text:004016F8		       push    [ebp+func]      ; func
.text:004016FB		       call    __onexit
.text:00401700		       neg     eax
.text:00401702		       pop     ecx
.text:00401703		       sbb     eax, eax
.text:00401705		       neg     eax
.text:00401707		       dec     eax
.text:00401708		       pop     ebp
.text:00401709		       retn
.text:00401709 _atexit	       endp
.text:00401709
.text:0040170A
.text:0040170A ; =============== S U B R O U T I N E =======================================
.text:0040170A
.text:0040170A
.text:0040170A __RTC_Initialize	proc near	       ; CODE XREF: pre_c_init+80p
.text:0040170A		       push    esi
.text:0040170B		       push    edi
.text:0040170C		       mov     esi, offset ___rtc_izz
.text:00401711		       mov     edi, offset ___rtc_izz
.text:00401716		       jmp     short loc_401723
.text:00401718 ; ---------------------------------------------------------------------------
.text:00401718
.text:00401718 loc_401718:			       ; CODE XREF: __RTC_Initialize+1Bj
.text:00401718		       mov     eax, [esi]
.text:0040171A		       test    eax, eax
.text:0040171C		       jz      short loc_401720
.text:0040171E		       call    eax
.text:00401720
.text:00401720 loc_401720:			       ; CODE XREF: __RTC_Initialize+12j
.text:00401720		       add     esi, 4
.text:00401723
.text:00401723 loc_401723:			       ; CODE XREF: __RTC_Initialize+Cj
.text:00401723		       cmp     esi, edi
.text:00401725		       jb      short loc_401718
.text:00401727		       pop     edi
.text:00401728		       pop     esi
.text:00401729		       retn
.text:00401729 __RTC_Initialize	endp
.text:00401729
.text:0040172A
.text:0040172A ; =============== S U B R O U T I N E =======================================
.text:0040172A
.text:0040172A
.text:0040172A ; void __cdecl _RTC_Terminate()
.text:0040172A __RTC_Terminate proc near	       ; DATA XREF: pre_cpp_inito
.text:0040172A		       push    esi
.text:0040172B		       push    edi
.text:0040172C		       mov     esi, offset ___rtc_tzz
.text:00401731		       mov     edi, offset ___rtc_tzz
.text:00401736		       jmp     short loc_401743
.text:00401738 ; ---------------------------------------------------------------------------
.text:00401738
.text:00401738 loc_401738:			       ; CODE XREF: __RTC_Terminate+1Bj
.text:00401738		       mov     eax, [esi]
.text:0040173A		       test    eax, eax
.text:0040173C		       jz      short loc_401740
.text:0040173E		       call    eax
.text:00401740
.text:00401740 loc_401740:			       ; CODE XREF: __RTC_Terminate+12j
.text:00401740		       add     esi, 4
.text:00401743
.text:00401743 loc_401743:			       ; CODE XREF: __RTC_Terminate+Cj
.text:00401743		       cmp     esi, edi
.text:00401745		       jb      short loc_401738
.text:00401747		       pop     edi
.text:00401748		       pop     esi
.text:00401749		       retn
.text:00401749 __RTC_Terminate endp
.text:00401749
.text:0040174A ; [00000028 BYTES: COLLAPSED FUNCTION __setdefaultprecision]
.text:00401772 ; [00000006 BYTES: COLLAPSED FUNCTION __initterm_e]
.text:00401778 ; [00000006 BYTES: COLLAPSED FUNCTION __initterm]
.text:0040177E		       align 10h
.text:00401780 ; [00000045 BYTES: COLLAPSED FUNCTION __SEH_prolog4]
.text:004017C5 ; [00000014 BYTES: COLLAPSED FUNCTION __SEH_epilog4]
.text:004017D9 ; [00000023 BYTES: COLLAPSED FUNCTION __except_handler4]
.text:004017FC ; [00000006 BYTES: COLLAPSED FUNCTION __crt_debugger_hook]
.text:00401802 ; [00000006 BYTES: COLLAPSED FUNCTION ___crtUnhandledException]
.text:00401808 ; [00000006 BYTES: COLLAPSED FUNCTION ___crtTerminateProcess]
.text:0040180E
.text:0040180E ; =============== S U B R O U T I N E =======================================
.text:0040180E
.text:0040180E ; Attributes: noreturn
.text:0040180E
.text:0040180E ; void __cdecl terminate()
.text:0040180E ?terminate@@YAXXZ_0 proc	near	       ; CODE XREF: __CxxUnhandledExceptionFilter(_EXCEPTION_POINTERS *):loc_401406p
.text:0040180E		       jmp     ds:__imp_?terminate@@YAXXZ ; terminate(void)
.text:0040180E ?terminate@@YAXXZ_0 endp
.text:0040180E
.text:00401814 ; [00000006 BYTES: COLLAPSED FUNCTION ___crtSetUnhandledExceptionFilter]
.text:0040181A ; [00000006 BYTES: COLLAPSED FUNCTION __lock]
.text:00401820 ; [00000006 BYTES: COLLAPSED FUNCTION __unlock]
.text:00401826 ; [00000006 BYTES: COLLAPSED FUNCTION ___dllonexit]
.text:0040182C ; [00000006 BYTES: COLLAPSED FUNCTION __invoke_watson]
.text:00401832 ; [00000006 BYTES: COLLAPSED FUNCTION __controlfp_s]
.text:00401838 ; [00000006 BYTES: COLLAPSED FUNCTION __except_handler4_common]
.text:0040183E ; [00000006 BYTES: COLLAPSED FUNCTION IsProcessorFeaturePresent(x)]
.text:00401844		       align 200h
.text:00401A00		       dd 180h dup(?)
.text:00401A00 _text	       ends
.text:00401A00
.idata:00402000	; Section 2. (virtual address 00002000)
.idata:00402000	; Virtual size			: 000005B4 (   1460.)
.idata:00402000	; Section size in file		: 00000600 (   1536.)
.idata:00402000	; Offset to raw	data for section: 00000E00
.idata:00402000	; Flags	40000040: Data Readable
.idata:00402000	; Alignment	: default
.idata:00402000	;
.idata:00402000	; Imports from KERNEL32.dll
.idata:00402000	;
.idata:00402000	; ===========================================================================
.idata:00402000
.idata:00402000	; Segment type:	Externs
.idata:00402000	; _idata
.idata:00402000	; void __stdcall GetSystemTimeAsFileTime(LPFILETIME lpSystemTimeAsFileTime)
.idata:00402000			extrn __imp__GetSystemTimeAsFileTime@4:dword
.idata:00402000						; CODE XREF: ___security_init_cookie+34p
.idata:00402000						; DATA XREF: ___security_init_cookie+34r ...
.idata:00402004	; DWORD	__stdcall GetCurrentThreadId()
.idata:00402004			extrn __imp__GetCurrentThreadId@0:dword
.idata:00402004						; CODE XREF: ___security_init_cookie+43p
.idata:00402004						; DATA XREF: ___security_init_cookie+43r
.idata:00402008	; DWORD	__stdcall GetCurrentProcessId()
.idata:00402008			extrn __imp__GetCurrentProcessId@0:dword
.idata:00402008						; CODE XREF: ___security_init_cookie+4Cp
.idata:00402008						; DATA XREF: ___security_init_cookie+4Cr
.idata:0040200C	; BOOL __stdcall QueryPerformanceCounter(LARGE_INTEGER *lpPerformanceCount)
.idata:0040200C			extrn __imp__QueryPerformanceCounter@4:dword
.idata:0040200C						; CODE XREF: ___security_init_cookie+59p
.idata:0040200C						; DATA XREF: ___security_init_cookie+59r
.idata:00402010	; BOOL __stdcall IsProcessorFeaturePresent(DWORD ProcessorFeature)
.idata:00402010			extrn __imp__IsProcessorFeaturePresent@4:dword
.idata:00402010						; DATA XREF: IsProcessorFeaturePresent(x)r
.idata:00402014	; BOOL __stdcall IsDebuggerPresent()
.idata:00402014			extrn __imp__IsDebuggerPresent@0:dword
.idata:00402014						; CODE XREF: ___raise_securityfailure+3p
.idata:00402014						; DATA XREF: ___raise_securityfailure+3r
.idata:00402018	; PVOID	__stdcall EncodePointer(PVOID Ptr)
.idata:00402018			extrn __imp__EncodePointer@4:dword
.idata:00402018						; CODE XREF: pre_c_init+56p
.idata:00402018						; ___atonexitinit+1Cp ...
.idata:0040201C	; PVOID	__stdcall DecodePointer(PVOID Ptr)
.idata:0040201C			extrn __imp__DecodePointer@4:dword ; CODE XREF:	__onexit+1Cp
.idata:0040201C						; __onexit+44p	...
.idata:00402020			extrn _KERNEL32_NULL_THUNK_DATA:byte:4
.idata:00402024	;
.idata:00402024	; Imports from MSVCR120.dll
.idata:00402024	;
.idata:00402024			extrn __imp____setusermatherr:dword
.idata:00402024						; CODE XREF: pre_c_init+98p
.idata:00402024						; DATA XREF: pre_c_init+98r ...
.idata:00402028			extrn __imp___initterm_e:dword ; DATA XREF: __initterm_er
.idata:0040202C			extrn __imp___initterm:dword ; DATA XREF: __inittermr
.idata:00402030			extrn __imp____winitenv:dword
.idata:00402030						; DATA XREF: __tmainCRTStartup+DFr
.idata:00402034	; int __fmode
.idata:00402034			extrn __imp___fmode:dword ; DATA XREF: pre_c_init+5Cr
.idata:00402038			extrn __imp___commode:dword ; DATA XREF: pre_c_init+73r
.idata:0040203C			extrn __imp___crt_debugger_hook:dword
.idata:0040203C						; DATA XREF: __crt_debugger_hookr
.idata:00402040			extrn __imp____crtUnhandledException:dword
.idata:00402040						; DATA XREF: ___crtUnhandledExceptionr
.idata:00402044			extrn __imp____crtTerminateProcess:dword
.idata:00402044						; DATA XREF: ___crtTerminateProcessr
.idata:00402048			extrn __imp___configthreadlocale:dword
.idata:00402048						; CODE XREF: pre_c_init+AFp
.idata:00402048						; DATA XREF: pre_c_init+AFr
.idata:0040204C	; __declspec(dllimport)	void __cdecl terminate(void)
.idata:0040204C			extrn __imp_?terminate@@YAXXZ:dword
.idata:0040204C						; DATA XREF: terminate(void)r
.idata:00402050			extrn __imp____crtSetUnhandledExceptionFilter:dword
.idata:00402050						; DATA XREF: ___crtSetUnhandledExceptionFilterr
.idata:00402054			extrn __imp___lock:dword ; DATA	XREF: __lockr
.idata:00402058			extrn __imp___unlock:dword ; DATA XREF:	__unlockr
.idata:0040205C			extrn __imp___calloc_crt:dword
.idata:0040205C						; CODE XREF: ___atonexitinit+11p
.idata:0040205C						; DATA XREF: ___atonexitinit+11r
.idata:00402060			extrn __imp____dllonexit:dword ; DATA XREF: ___dllonexitr
.idata:00402064	; _onexit_t __cdecl __onexit(_onexit_t Func)
.idata:00402064			extrn __imp___onexit:dword ; CODE XREF:	__onexit+29p
.idata:00402064						; DATA XREF: __onexit+29r
.idata:00402068			extrn __imp___invoke_watson:dword
.idata:00402068						; DATA XREF: __invoke_watsonr
.idata:0040206C	; errno_t __cdecl __controlfp_s(unsigned int *CurrentState, unsigned int NewValue, unsigned int	Mask)
.idata:0040206C			extrn __imp___controlfp_s:dword	; DATA XREF: __controlfp_sr
.idata:00402070			extrn __imp___except_handler4_common:dword
.idata:00402070						; DATA XREF: __except_handler4_commonr
.idata:00402074	; void __cdecl __cexit()
.idata:00402074			extrn __imp___cexit:dword
.idata:00402074						; CODE XREF: __tmainCRTStartup+14Dp
.idata:00402074						; DATA XREF: __tmainCRTStartup+14Dr
.idata:00402078	; void __cdecl __noreturn __exit(int Code)
.idata:00402078			extrn __imp___exit:dword ; CODE	XREF: __tmainCRTStartup+13Ep
.idata:00402078						; DATA XREF: __tmainCRTStartup+13Er
.idata:0040207C	; void __cdecl __noreturn _exit(int Code)
.idata:0040207C			extrn __imp__exit:dword	; CODE XREF: __tmainCRTStartup+10Fp
.idata:0040207C						; DATA XREF: __tmainCRTStartup+10Fr
.idata:00402080			extrn __imp____set_app_type:dword
.idata:00402080						; CODE XREF: pre_c_init+4Dp
.idata:00402080						; DATA XREF: pre_c_init+4Dr
.idata:00402084			extrn __imp____wgetmainargs:dword
.idata:00402084						; CODE XREF: pre_cpp_init+30p
.idata:00402084						; DATA XREF: pre_cpp_init+30r
.idata:00402088			extrn __imp___amsg_exit:dword ;	DATA XREF: __amsg_exitr
.idata:0040208C			extrn __imp___XcptFilter:dword ; DATA XREF: __XcptFilterr
.idata:00402090	; int _wprintf(const wchar_t *Format, ...)
.idata:00402090			extrn __imp__wprintf:dword ; CODE XREF:	_main+5p
.idata:00402090						; DATA XREF: _main+5r
.idata:00402094			extrn _MSVCR120_NULL_THUNK_DATA:byte:4
.idata:00402094
.rdata:00402098	; ===========================================================================
.rdata:00402098
.rdata:00402098	; Segment type:	Pure data
.rdata:00402098	; Segment permissions: Read
.rdata:00402098	_rdata		segment	para public 'DATA' use32
.rdata:00402098			assume cs:_rdata
.rdata:00402098			;org 402098h
.rdata:00402098	___xc_a		dd 0			; DATA XREF: __tmainCRTStartup+94o
.rdata:0040209C	; void (__cdecl	*pcppinit)()
.rdata:0040209C	pcppinit	dd offset pre_cpp_init
.rdata:004020A0	___xc_z		dd 0			; DATA XREF: __tmainCRTStartup+8Fo
.rdata:004020A4	___xi_a		dd 0			; DATA XREF: __tmainCRTStartup+60o
.rdata:004020A8	; int (__cdecl *pcinit)()
.rdata:004020A8	pcinit		dd offset pre_c_init
.rdata:004020AC	; int (__cdecl *pinit)()
.rdata:004020AC	pinit		dd offset ___atonexitinit
.rdata:004020B0	; int (__cdecl *pinit_0)()
.rdata:004020B0	pinit_0		dd offset ___CxxSetUnhandledExceptionFilter
.rdata:004020B4	___xi_z		dd 3 dup(0)		; DATA XREF: __tmainCRTStartup+5Bo
.rdata:004020C0	; Debug	Directory entries
.rdata:004020C0			dd 0			; Characteristics
.rdata:004020C4			dd 5A641C0Dh		; TimeDateStamp: Sun Jan 21 04:50:21 2018
.rdata:004020C8			dw 0			; MajorVersion
.rdata:004020CA			dw 0			; MinorVersion
.rdata:004020CC			dd 2			; Type:	IMAGE_DEBUG_TYPE_CODEVIEW
.rdata:004020D0			dd 56h			; SizeOfData
.rdata:004020D4			dd rva asc_402168	; AddressOfRawData
.rdata:004020D8			dd 0F68h		; PointerToRawData
.rdata:004020DC			dd 0			; Characteristics
.rdata:004020E0			dd 5A641C0Dh		; TimeDateStamp: Sun Jan 21 04:50:21 2018
.rdata:004020E4			dw 0			; MajorVersion
.rdata:004020E6			dw 0			; MinorVersion
.rdata:004020E8			dd 0Ch			; Type
.rdata:004020EC			dd 14h			; SizeOfData
.rdata:004020F0			dd rva dword_4021C0	; AddressOfRawData
.rdata:004020F4			dd 0FC0h		; PointerToRawData
.rdata:004020F8	; _EXCEPTION_POINTERS GS_ExceptionPointers
.rdata:004020F8	GS_ExceptionPointers _EXCEPTION_POINTERS <offset GS_ExceptionRecord, \
.rdata:004020F8						; DATA XREF: ___report_gsfailure+EDo
.rdata:004020F8					     offset GS_ContextRecord>
.rdata:00402100	; wchar_t Format
.rdata:00402100	Format:					; DATA XREF: _maino
.rdata:00402100			unicode	0, <Hello World!>
.rdata:00402100			dw 0Ah,	0
.rdata:0040211C			align 10h
.rdata:00402120	__load_config_used dd 48h		; Size
.rdata:00402124			dd 0			; Time stamp
.rdata:00402128			dw 2 dup(0)		; Version: 0.0
.rdata:0040212C			dd 0			; GlobalFlagsClear
.rdata:00402130			dd 0			; GlobalFlagsSet
.rdata:00402134			dd 0			; CriticalSectionDefaultTimeout
.rdata:00402138			dd 0			; DeCommitFreeBlockThreshold
.rdata:0040213C			dd 0			; DeCommitTotalFreeThreshold
.rdata:00402140			dd 0			; LockPrefixTable
.rdata:00402144			dd 0			; MaximumAllocationSize
.rdata:00402148			dd 0			; VirtualMemoryThreshold
.rdata:0040214C			dd 0			; ProcessAffinityMask
.rdata:00402150			dd 0			; ProcessHeapFlags
.rdata:00402154			dw 0			; CSDVersion
.rdata:00402156			dw 0			; Reserved1
.rdata:00402158			dd 0			; EditList
.rdata:0040215C			dd offset ___security_cookie ; SecurityCookie
.rdata:00402160			dd offset ___safe_se_handler_table ; SEHandlerTable
.rdata:00402164			dd 1			; SEHandlerCount
.rdata:00402168	; Debug	information (IMAGE_DEBUG_TYPE_CODEVIEW)
.rdata:00402168	asc_402168	db 'RSDS'               ; DATA XREF: .rdata:004020D4o
.rdata:00402168						; CV signature
.rdata:0040216C			dd 5101A389h		; Data1	; GUID
.rdata:0040216C			dw 0E7Ch		; Data2
.rdata:0040216C			dw 4CA2h		; Data3
.rdata:0040216C			db 99h,	72h, 84h, 67h, 0BBh, 36h, 0B5h,	0C3h; Data4
.rdata:0040217C			dd 1			; Age
.rdata:00402180			db 'C:\Users\John\Desktop\Win32Project1\Release\Win32Project1.pdb',0 ; PdbFileName
.rdata:004021BE			align 10h
.rdata:004021C0	; Debug	information (type 12)
.rdata:004021C0	dword_4021C0	dd 0			; DATA XREF: .rdata:004020F0o
.rdata:004021C4			dd 2 dup(17h), 2, 4 dup(0)
.rdata:004021E0	___safe_se_handler_table dd rva	__except_handler4
.rdata:004021E0						; DATA XREF: .rdata:00402160o
.rdata:004021E4	___rtc_iaa	dd 0
.rdata:004021E8	___rtc_izz	dd 0			; DATA XREF: __RTC_Initialize+2o
.rdata:004021E8						; __RTC_Initialize+7o
.rdata:004021EC	___rtc_taa	dd 0
.rdata:004021F0	___rtc_tzz	dd 2 dup(0)		; DATA XREF: __RTC_Terminate+2o
.rdata:004021F0						; __RTC_Terminate+7o
.rdata:004021F8	stru_4021F8	dd 0FFFFFFFEh		; GSCookieOffset
.rdata:004021F8						; DATA XREF: __tmainCRTStartup+2o
.rdata:004021F8			dd 0			; GSCookieXOROffset ; SEH scope	table for function 401124
.rdata:004021F8			dd 0FFFFFFD4h		; EHCookieOffset
.rdata:004021F8			dd 0			; EHCookieXOROffset
.rdata:004021F8			dd 0FFFFFFFEh		; ScopeRecord.EnclosingLevel
.rdata:004021F8			dd offset $LN35		; ScopeRecord.FilterFunc
.rdata:004021F8			dd offset $LN21		; ScopeRecord.HandlerFunc
.rdata:00402214			align 8
.rdata:00402218	stru_402218	dd 0FFFFFFFEh		; GSCookieOffset
.rdata:00402218						; DATA XREF: __IsNonwritableInCurrentImage+5o
.rdata:00402218			dd 0			; GSCookieXOROffset ; SEH scope	table for function 401480
.rdata:00402218			dd 0FFFFFFD8h		; EHCookieOffset
.rdata:00402218			dd 0			; EHCookieXOROffset
.rdata:00402218			dd 0FFFFFFFEh		; ScopeRecord.EnclosingLevel
.rdata:00402218			dd offset $LN7		; ScopeRecord.FilterFunc
.rdata:00402218			dd offset $LN8_0	; ScopeRecord.HandlerFunc
.rdata:00402234			align 8
.rdata:00402238	stru_402238	dd 0FFFFFFFEh		; GSCookieOffset
.rdata:00402238						; DATA XREF: __onexit+2o
.rdata:00402238			dd 0			; GSCookieXOROffset ; SEH scope	table for function 40164C
.rdata:00402238			dd 0FFFFFFCCh		; EHCookieOffset
.rdata:00402238			dd 0			; EHCookieXOROffset
.rdata:00402238			dd 0FFFFFFFEh		; ScopeRecord.EnclosingLevel
.rdata:00402238			dd 0			; ScopeRecord.FilterFunc
.rdata:00402238			dd offset $LN6		; ScopeRecord.HandlerFunc
.rdata:00402254	__IMPORT_DESCRIPTOR_MSVCR120 dd	rva off_4022B4 ; Import	Name Table
.rdata:00402258			dd 0			; Time stamp
.rdata:0040225C			dd 0			; Forwarder Chain
.rdata:00402260			dd rva aMsvcr120_dll	; DLL Name
.rdata:00402264			dd rva __imp____setusermatherr ; Import	Address	Table
.rdata:00402268	__IMPORT_DESCRIPTOR_KERNEL32 dd	rva off_402290 ; Import	Name Table
.rdata:0040226C			dd 0			; Time stamp
.rdata:00402270			dd 0			; Forwarder Chain
.rdata:00402274			dd rva aKernel32_dll	; DLL Name
.rdata:00402278			dd rva __imp__GetSystemTimeAsFileTime@4	; Import Address Table
.rdata:0040227C	__NULL_IMPORT_DESCRIPTOR dd 5 dup(0)
.rdata:00402290	;
.rdata:00402290	; Import names for KERNEL32.dll
.rdata:00402290	;
.rdata:00402290	off_402290	dd rva word_40257C	; DATA XREF: .rdata:__IMPORT_DESCRIPTOR_KERNEL32o
.rdata:00402294			dd rva word_402566
.rdata:00402298			dd rva word_402550
.rdata:0040229C			dd rva word_402536
.rdata:004022A0			dd rva word_40251A
.rdata:004022A4			dd rva word_402506
.rdata:004022A8			dd rva word_4024F6
.rdata:004022AC			dd rva word_402596
.rdata:004022B0			dd 0
.rdata:004022B4	;
.rdata:004022B4	; Import names for MSVCR120.dll
.rdata:004022B4	;
.rdata:004022B4	off_4022B4	dd rva word_4023B0	; DATA XREF: .rdata:__IMPORT_DESCRIPTOR_MSVCR120o
.rdata:004022B8			dd rva word_4023C4
.rdata:004022BC			dd rva word_4023D2
.rdata:004022C0			dd rva word_4023DE
.rdata:004022C4			dd rva word_4023EC
.rdata:004022C8			dd rva word_4023F6
.rdata:004022CC			dd rva word_402402
.rdata:004022D0			dd rva word_402418
.rdata:004022D4			dd rva word_402432
.rdata:004022D8			dd rva word_40239A
.rdata:004022DC			dd rva word_40244A
.rdata:004022E0			dd rva word_40245E
.rdata:004022E4			dd rva word_402482
.rdata:004022E8			dd rva word_40248A
.rdata:004022EC			dd rva word_402494
.rdata:004022F0			dd rva word_4024A2
.rdata:004022F4			dd rva word_4024B0
.rdata:004022F8			dd rva word_4024BA
.rdata:004022FC			dd rva word_4024CC
.rdata:00402300			dd rva word_4024DC
.rdata:00402304			dd rva word_402390
.rdata:00402308			dd rva word_402388
.rdata:0040230C			dd rva word_402380
.rdata:00402310			dd rva word_40236E
.rdata:00402314			dd rva word_40235C
.rdata:00402318			dd rva word_40234E
.rdata:0040231C			dd rva word_402340
.rdata:00402320			dd rva word_402328
.rdata:00402324			dd 0
.rdata:00402328	word_402328	dw 7AAh			; DATA XREF: .rdata:00402320o
.rdata:0040232A			db 'wprintf',0
.rdata:00402332	aMsvcr120_dll	db 'MSVCR120.dll',0     ; DATA XREF: .rdata:00402260o
.rdata:0040233F			align 10h
.rdata:00402340	word_402340	dw 16Bh			; DATA XREF: .rdata:0040231Co
.rdata:00402342			db '_XcptFilter',0
.rdata:0040234E	word_40234E	dw 217h			; DATA XREF: .rdata:00402318o
.rdata:00402350			db '_amsg_exit',0
.rdata:0040235B			align 4
.rdata:0040235C	word_40235C	dw 208h			; DATA XREF: .rdata:00402314o
.rdata:0040235E			db '__wgetmainargs',0
.rdata:0040236D			align 2
.rdata:0040236E	word_40236E	dw 1F2h			; DATA XREF: .rdata:00402310o
.rdata:00402370			db '__set_app_type',0
.rdata:0040237F			align 10h
.rdata:00402380	word_402380	dw 64Eh			; DATA XREF: .rdata:0040230Co
.rdata:00402382			db 'exit',0
.rdata:00402387			align 4
.rdata:00402388	word_402388	dw 283h			; DATA XREF: .rdata:00402308o
.rdata:0040238A			db '_exit',0
.rdata:00402390	word_402390	dw 22Fh			; DATA XREF: .rdata:00402304o
.rdata:00402392			db '_cexit',0
.rdata:00402399			align 2
.rdata:0040239A	word_40239A	dw 240h			; DATA XREF: .rdata:004022D8o
.rdata:0040239C			db '_configthreadlocale',0
.rdata:004023B0	word_4023B0	dw 1F4h			; DATA XREF: .rdata:off_4022B4o
.rdata:004023B2			db '__setusermatherr',0
.rdata:004023C3			align 4
.rdata:004023C4	word_4023C4	dw 30Dh			; DATA XREF: .rdata:004022B8o
.rdata:004023C6			db '_initterm_e',0
.rdata:004023D2	word_4023D2	dw 30Ch			; DATA XREF: .rdata:004022BCo
.rdata:004023D4			db '_initterm',0
.rdata:004023DE	word_4023DE	dw 209h			; DATA XREF: .rdata:004022C0o
.rdata:004023E0			db '__winitenv',0
.rdata:004023EB			align 4
.rdata:004023EC	word_4023EC	dw 2A2h			; DATA XREF: .rdata:004022C4o
.rdata:004023EE			db '_fmode',0
.rdata:004023F5			align 2
.rdata:004023F6	word_4023F6	dw 23Fh			; DATA XREF: .rdata:004022C8o
.rdata:004023F8			db '_commode',0
.rdata:00402401			align 2
.rdata:00402402	word_402402	dw 250h			; DATA XREF: .rdata:004022CCo
.rdata:00402404			db '_crt_debugger_hook',0
.rdata:00402417			align 4
.rdata:00402418	word_402418	dw 1ACh			; DATA XREF: .rdata:004022D0o
.rdata:0040241A			db '__crtUnhandledException',0
.rdata:00402432	word_402432	dw 1ABh			; DATA XREF: .rdata:004022D4o
.rdata:00402434			db '__crtTerminateProcess',0
.rdata:0040244A	word_40244A	dw 135h			; DATA XREF: .rdata:004022DCo
.rdata:0040244C			db '?terminate@@YAXXZ',0
.rdata:0040245E	word_40245E	dw 1A9h			; DATA XREF: .rdata:004022E0o
.rdata:00402460			db '__crtSetUnhandledExceptionFilter',0
.rdata:00402481			align 2
.rdata:00402482	word_402482	dw 394h			; DATA XREF: .rdata:004022E4o
.rdata:00402484			db '_lock',0
.rdata:0040248A	word_40248A	dw 504h			; DATA XREF: .rdata:004022E8o
.rdata:0040248C			db '_unlock',0
.rdata:00402494	word_402494	dw 22Eh			; DATA XREF: .rdata:004022ECo
.rdata:00402496			db '_calloc_crt',0
.rdata:004024A2	word_4024A2	dw 1AEh			; DATA XREF: .rdata:004022F0o
.rdata:004024A4			db '__dllonexit',0
.rdata:004024B0	word_4024B0	dw 43Ah			; DATA XREF: .rdata:004022F4o
.rdata:004024B2			db '_onexit',0
.rdata:004024BA	word_4024BA	dw 314h			; DATA XREF: .rdata:004022F8o
.rdata:004024BC			db '_invoke_watson',0
.rdata:004024CB			align 4
.rdata:004024CC	word_4024CC	dw 243h			; DATA XREF: .rdata:004022FCo
.rdata:004024CE			db '_controlfp_s',0
.rdata:004024DB			align 4
.rdata:004024DC	word_4024DC	dw 27Ah			; DATA XREF: .rdata:00402300o
.rdata:004024DE			db '_except_handler4_common',0
.rdata:004024F6	word_4024F6	dw 121h			; DATA XREF: .rdata:004022A8o
.rdata:004024F8			db 'EncodePointer',0
.rdata:00402506	word_402506	dw 367h			; DATA XREF: .rdata:004022A4o
.rdata:00402508			db 'IsDebuggerPresent',0
.rdata:0040251A	word_40251A	dw 36Dh			; DATA XREF: .rdata:004022A0o
.rdata:0040251C			db 'IsProcessorFeaturePresent',0
.rdata:00402536	word_402536	dw 42Dh			; DATA XREF: .rdata:0040229Co
.rdata:00402538			db 'QueryPerformanceCounter',0
.rdata:00402550	word_402550	dw 20Ah			; DATA XREF: .rdata:00402298o
.rdata:00402552			db 'GetCurrentProcessId',0
.rdata:00402566	word_402566	dw 20Eh			; DATA XREF: .rdata:00402294o
.rdata:00402568			db 'GetCurrentThreadId',0
.rdata:0040257B			align 4
.rdata:0040257C	word_40257C	dw 2D6h			; DATA XREF: .rdata:off_402290o
.rdata:0040257E			db 'GetSystemTimeAsFileTime',0
.rdata:00402596	word_402596	dw 0FEh			; DATA XREF: .rdata:004022ACo
.rdata:00402598			db 'DecodePointer',0
.rdata:004025A6	aKernel32_dll	db 'KERNEL32.dll',0     ; DATA XREF: .rdata:00402274o
.rdata:004025B3			align 1000h
.rdata:004025B3	_rdata		ends
.rdata:004025B3
.data:00403000 ; Section 3. (virtual address 00003000)
.data:00403000 ; Virtual size		       : 00000380 (    896.)
.data:00403000 ; Section size in file	       : 00000200 (    512.)
.data:00403000 ; Offset	to raw data for	section: 00001400
.data:00403000 ; Flags C0000040: Data Readable Writable
.data:00403000 ; Alignment     : default
.data:00403000 ; ===========================================================================
.data:00403000
.data:00403000 ; Segment type: Pure data
.data:00403000 ; Segment permissions: Read/Write
.data:00403000 _data	       segment para public 'DATA' use32
.data:00403000		       assume cs:_data
.data:00403000		       ;org 403000h
.data:00403000 ___security_cookie dd 0BB40E64Eh	       ; DATA XREF: __security_check_cookie(x)r
.data:00403000					       ; ___report_gsfailure+D3r ...
.data:00403004 ___security_cookie_complement dd	44BF19B1h
.data:00403004					       ; DATA XREF: ___report_gsfailure+E3r
.data:00403004					       ; ___security_init_cookie+29w ...
.data:00403008 ___defaultmatherr dd 1		       ; DATA XREF: pre_c_init+8Ar
.data:0040300C		       align 10h
.data:00403010 ___globallocalestatus dd	0FFFFFFFEh     ; DATA XREF: pre_c_init+A4r
.data:00403014 ___native_dllmain_reason	dd 0FFFFFFFFh
.data:00403018 ; int has_cctor
.data:00403018 has_cctor       dd 0		       ; DATA XREF: __tmainCRTStartup:loc_4011A5w
.data:00403018					       ; __tmainCRTStartup:$LN36r
.data:0040301C ; int mainret
.data:0040301C mainret	       dd 0		       ; DATA XREF: __tmainCRTStartup+100w
.data:0040301C					       ; __tmainCRTStartup+12Fw ...
.data:00403020 ; int managedapp
.data:00403020 managedapp      dd 0		       ; DATA XREF: pre_c_init+48w
.data:00403020					       ; __tmainCRTStartup+105r ...
.data:00403024 ; int argc
.data:00403024 argc	       dd 0		       ; DATA XREF: pre_cpp_init+2Bo
.data:00403024					       ; __tmainCRTStartup+F2r
.data:00403028 ; char **argv
.data:00403028 argv	       dd 0		       ; DATA XREF: pre_cpp_init+26o
.data:00403028					       ; __tmainCRTStartup+ECr
.data:0040302C ; char **envp
.data:0040302C envp	       dd 0		       ; DATA XREF: pre_cpp_init+21o
.data:0040302C					       ; __tmainCRTStartup:loc_4011FDr	...
.data:00403030 ; int argret
.data:00403030 argret	       dd 0		       ; DATA XREF: pre_cpp_init+39w
.data:00403034 ; _startupinfo startinfo
.data:00403034 startinfo       _startupinfo <0>	       ; DATA XREF: pre_cpp_init+Fo
.data:00403034					       ; pre_cpp_init+1Cw
.data:00403038 ; _EXCEPTION_RECORD GS_ExceptionRecord
.data:00403038 GS_ExceptionRecord _EXCEPTION_RECORD <0>	; DATA XREF: ___report_gsfailure+9Fw
.data:00403038					       ; .rdata:GS_ExceptionPointerso ...
.data:00403088 ; _CONTEXT GS_ContextRecord
.data:00403088 GS_ContextRecord	_CONTEXT <?>	       ; DATA XREF: ___report_gsfailure+8Bw
.data:00403088					       ; .rdata:GS_ExceptionPointerso
.data:00403354 ; int DebuggerWasPresent
.data:00403354 DebuggerWasPresent dd ?		       ; DATA XREF: ___raise_securityfailure+Bw
.data:00403354					       ; ___raise_securityfailure+1Dr
.data:00403358 __commode       dd ?		       ; DATA XREF: pre_c_init+79r
.data:0040335C __dowildcard    dd ?		       ; DATA XREF: pre_cpp_init+16r
.data:00403360 __newmode       dd ?		       ; DATA XREF: pre_cpp_init+Ar
.data:00403364 ; int _fmode
.data:00403364 __fmode	       dd ?		       ; DATA XREF: pre_c_init+6Cr
.data:00403368 ___@@_PchSym_@00@UfhvihUqlsmUwvhpglkUdrmDCkilqvxgBUdrmDCkilqvxgBUivovzhvUhgwzucOlyq@AF4C624794DF9117 dd ?
.data:0040336C ___native_startup_lock dd ?	       ; DATA XREF: __tmainCRTStartup+1Co
.data:0040336C					       ; __tmainCRTStartup+B0o
.data:00403370 ___native_startup_state dd ?	       ; DATA XREF: __tmainCRTStartup:loc_40115Fr
.data:00403370					       ; __tmainCRTStartup:loc_401171r	...
.data:00403374 ; PVOID __onexitend
.data:00403374 ___onexitend    dd ?		       ; DATA XREF: pre_c_init+62w
.data:00403374					       ; ___atonexitinit+27w ...
.data:00403378 ; PVOID __onexitbegin
.data:00403378 ___onexitbegin  dd ?		       ; DATA XREF: pre_c_init+67w
.data:00403378					       ; ___atonexitinitr ...
.data:0040337C ; char __dyn_tls_init_callback[]
.data:0040337C ___dyn_tls_init_callback	dd ?	       ; DATA XREF: __tmainCRTStartup:loc_4011DBr
.data:0040337C					       ; __tmainCRTStartup+C0o	...
.data:00403380		       align 1000h
.data:00403380 _data	       ends
.data:00403380
.data:00403380
.data:00403380		       end _wmainCRTStartup
